version: "3.9"

services:
  provider:
    image: edc-ionos-provider:latest
    ports:
      - "8181:8181"
      - "8182:8182"
      - "8282:8282"
    environment:
      EDC_FS_CONFIG: /resources/provider-config.properties
  consumer:
    image: edc-ionos-consumer:latest
    ports:
      - "9191:9191"
      - "9192:9192"
      - "9292:9292"
    environment:
      EDC_FS_CONFIG: /resources/consumer-config.properties